const viLocale = {
  assetManager: {
    addButton: 'Thêm ảnh',
    inputPlh: 'http://đường-dẫn-ảnh.jpg',
    modalTitle: 'Chọn ảnh',
    uploadTitle: 'Kéo thả file vào đây hoặc click để tải lên'
  },
  blockManager: {
    labels: {
      '1 Column': '1 Cột',
      '2 Columns': '2 Cột',
      '3 Columns': '3 Cột',
      '3/7 Columns': 'Cột 3/7',
      'Text': 'Văn bản',
      'Link': 'Liên kết',
      'Image': 'Hình ảnh',
      'Video': 'Video',
      'Map': 'Bản đồ',
      'Text section': 'Đoạn văn bản',
      'Link block': 'Khối liên kết',
      'Quote': 'Trích dẫn',
      'link-block': 'Khối liên kết',
      'quote': 'Trích dẫn',
      'text-basic': 'Đoạn văn bản',
      'column1': '1 Cột',
      'column2': '2 Cột',
      'column3': '3 Cột',
      'column3-7': 'Cột 3/7',
      'text': 'Văn bản',
      'link': 'Liên kết',
      'image': 'Hình ảnh',
      'video': 'Video',
      'map': 'Bản đồ',
      'form': 'Biểu mẫu',
      'input': 'Ô nhập liệu',
      'textarea': 'Ô nhập văn bản',
      'select': 'Khối lựa chọn',
      'checkbox': 'Hộp kiểm',
      'radio': 'Nút radio',
      'button': 'Nút bấm',
      'label': 'Nhãn'
    },
    categories: {
      'Basic': 'Cơ bản',
      'Extra': 'Mở rộng',
      'Forms': 'Biểu mẫu',
      'Typography': 'Văn bản'
    }
  },
  domComponents: {
    names: {
      '': 'Khối',
      wrapper: 'Phần thân',
      text: 'Văn bản',
      comment: 'Bình luận',
      image: 'Hình ảnh',
      video: 'Video',
      label: 'Nhãn',
      link: 'Liên kết',
      map: 'Bản đồ',
      tfoot: 'Chân bảng',
      tbody: 'Thân bảng',
      thead: 'Đầu bảng',
      table: 'Bảng',
      row: 'Hàng',
      cell: 'Ô'
    }
  },
  deviceManager: {
    device: 'Thiết bị',
    devices: {
      desktop: 'Máy tính',
      tablet: 'Máy tính bảng',
      mobileLandscape: 'Di động ngang',
      mobilePortrait: 'Di động dọc'
    }
  },
  panels: {
    buttons: {
      titles: {
        preview: 'Xem thử',
        fullscreen: 'Toàn màn hình',
        'sw-visibility': 'Hiển thị viền các thành phần',
        'export-template': 'Xem mã nguồn',
        'open-sm': 'Chỉnh sửa giao diện (CSS)',
        'open-tm': 'Cài đặt thuộc tính',
        'open-layers': 'Quản lý các lớp (Layers)',
        'open-blocks': 'Thêm khối (Blocks)',
        'cmd-clear': 'Xóa toàn bộ trang',
        'undo': 'Hoàn tác (Undo)',
        'redo': 'Làm lại (Redo)'
      }
    }
  },
  selectorManager: {
    label: 'Các lớp (Classes)',
    selected: 'Đã chọn',
    emptyState: '- Trạng thái -',
    states: {
      hover: 'Khi trỏ chuột (Hover)',
      active: 'Khi click (Active)',
      'nth-of-type(2n)': 'Chẵn/Lẻ'
    }
  },
  styleManager: {
    empty: 'Chọn 1 phần tử trước để chỉnh sửa giao diện',
    layer: 'Lớp',
    fileButton: 'Hình ảnh',
    sectors: {
      General: 'Chung',
      Layout: 'Bố cục',
      Typography: 'Kiểu chữ',
      Decorations: 'Trang trí',
      Extra: 'Mở rộng',
      Flex: 'Bố cục Flex',
      Dimension: 'Kích thước',
      general: 'Chung',
      layout: 'Bố cục',
      typography: 'Kiểu chữ',
      decorations: 'Trang trí',
      extra: 'Mở rộng',
      flex: 'Bố cục Flex',
      dimension: 'Kích thước'
    },
    properties: {
      'Display': 'Hiển thị',
      'display': 'Hiển thị',
      'Float': 'Căn lề (Float)',
      'float': 'Căn lề (Float)',
      'Position': 'Vị trí',
      'position': 'Vị trí',
      'Top': 'Trên',
      'top': 'Trên',
      'Right': 'Phải',
      'right': 'Phải',
      'Bottom': 'Dưới',
      'bottom': 'Dưới',
      'Left': 'Trái',
      'left': 'Trái',
      'Width': 'Chiều rộng',
      'width': 'Chiều rộng',
      'Height': 'Chiều cao',
      'height': 'Chiều cao',
      'Max width': 'Rộng tối đa',
      'max-width': 'Rộng tối đa',
      'Min height': 'Cao tối thiểu',
      'min-height': 'Cao tối thiểu',
      'Margin': 'Lề ngoài (Margin)',
      'margin': 'Lề ngoài (Margin)',
      'Padding': 'Lề trong (Padding)',
      'padding': 'Lề trong (Padding)',
      'Font family': 'Phông chữ',
      'font-family': 'Phông chữ',
      'Font size': 'Cỡ chữ',
      'font-size': 'Cỡ chữ',
      'Font weight': 'Độ dày chữ',
      'font-weight': 'Độ dày chữ',
      'Letter spacing': 'Khoảng cách chữ',
      'letter-spacing': 'Khoảng cách chữ',
      'Color': 'Màu sắc',
      'color': 'Màu sắc',
      'Line height': 'Chiều cao dòng',
      'line-height': 'Chiều cao dòng',
      'Text align': 'Căn chữ',
      'text-align': 'Căn chữ',
      'Text shadow': 'Bóng chữ',
      'text-shadow': 'Bóng chữ',
      'Opacity': 'Độ mờ',
      'opacity': 'Độ mờ',
      'Background color': 'Màu nền',
      'background-color': 'Màu nền',
      'Border radius': 'Bo góc',
      'border-radius': 'Bo góc',
      'Border': 'Viền',
      'border': 'Viền',
      'Box shadow': 'Bóng khối',
      'box-shadow': 'Bóng khối',
      'Background': 'Nền',
      'background': 'Nền',
      'Transition': 'Hiệu ứng chuyển',
      'transition': 'Hiệu ứng chuyển',
      'Perspective': 'Phối cảnh',
      'perspective': 'Phối cảnh',
      'Transform': 'Biến đổi',
      'transform': 'Biến đổi',
      'Flex direction': 'Hướng Flex',
      'flex-direction': 'Hướng Flex',
      'Flex wrap': 'Xuống dòng',
      'flex-wrap': 'Xuống dòng',
      'Justify content': 'Căn ngang',
      'justify-content': 'Căn ngang',
      'Align items': 'Căn dọc',
      'align-items': 'Căn dọc',
      'Align content': 'Căn khối dọc',
      'align-content': 'Căn khối dọc',
      'Align self': 'Căn cá nhân',
      'align-self': 'Căn cá nhân',
      'text-shadow-h': 'Ngang',
      'text-shadow-v': 'Dọc',
      'text-shadow-blur': 'Mờ',
      'text-shadow-color': 'Màu',
      'box-shadow-h': 'Ngang',
      'box-shadow-v': 'Dọc',
      'box-shadow-blur': 'Mờ',
      'box-shadow-spread': 'Lan rộng',
      'box-shadow-color': 'Màu',
      'box-shadow-type': 'Loại',
      'margin-top-sub': 'Đầu',
      'margin-right-sub': 'Phải',
      'margin-bottom-sub': 'Dưới',
      'margin-left-sub': 'Trái',
      'padding-top-sub': 'Đầu',
      'padding-right-sub': 'Phải',
      'padding-bottom-sub': 'Dưới',
      'padding-left-sub': 'Trái',
      'border-width-sub': 'Độ dày',
      'border-style-sub': 'Kiểu',
      'border-color-sub': 'Màu',
      'border-top-left-radius-sub': 'Góc trên trái',
      'border-top-right-radius-sub': 'Góc trên phải',
      'border-bottom-right-radius-sub': 'Góc dưới phải',
      'border-bottom-left-radius-sub': 'Góc dưới trái',
      'transform-rotate-x': 'Xoay X',
      'transform-rotate-y': 'Xoay Y',
      'transform-rotate-z': 'Xoay Z',
      'transform-scale-x': 'Phóng X',
      'transform-scale-y': 'Phóng Y',
      'transform-scale-z': 'Phóng Z',
      'transition-property-sub': 'Thuộc tính',
      'transition-duration-sub': 'Thời gian',
      'transition-timing-function-sub': 'Gia tốc',
      'background-image-sub': 'Ảnh',
      'background-repeat-sub': 'Lặp',
      'background-position-sub': 'Vị trí',
      'background-attachment-sub': 'Đính kèm',
      'background-size-sub': 'Kích thước'
    }
  },
  traitManager: {
    empty: 'Chọn 1 phần tử trước để cài đặt thuộc tính',
    label: 'Thuộc tính',
    traits: {
      attributes: {
        id: { placeholder: 'ví dụ: my-element' },
        alt: { placeholder: 'Văn bản thay thế' },
        title: { placeholder: 'ví dụ: Chú thích' },
        href: { placeholder: 'Ví dụ: https://google.com' }
      },
      options: {
        target: {
          false: 'Cửa sổ hiện tại',
          _blank: 'Cửa sổ mới'
        }
      }
    }
  },
  storageManager: {
    recover: 'Bạn có muốn khôi phục những thay đổi chưa được lưu?'
  }
};

export default viLocale;
