<USER_REQUEST>
tá»« tá»« hold láº¡i tÃ½, tÃ´i cÃ³ cÃ i sáºµn postgreSQL r vÃ  cÃ³ viáº¿t truy váº¥n db sáºµn r :

-- ============================================================
--  CELESTIA TOURISM MANAGEMENT SYSTEM
--  PostgreSQL Schema v1.0
--  Requires: PostgreSQL 14+
--  Encoding: UTF8
-- ============================================================
--  Summary
--    Tables     : 34
--    ENUM types : 14
--    Views      : 4
--    Functions  : 6
--    Triggers   : 16
-- ============================================================

BEGIN;

-- ============================================================
-- SECTION 0: ENUM TYPES
-- ============================================================

CREATE TYPE destination_status_t  AS ENUM ('draft', 'published', 'archived');
CREATE TYPE article_status_t      AS ENUM ('draft', 'review', 'published', 'archived');
CREATE TYPE review_status_t       AS ENUM ('pending', 'approved', 'rejected', 'flagged');
CREATE TYPE comment_status_t      AS ENUM ('pending', 'approved', 'rejected', 'flagged');
CREATE TYPE media_type_t          AS ENUM ('image', 'video', 'audio', 'document');
CREATE TYPE media_role_t          AS ENUM ('cover', 'thumbnail', 'gallery', 'video', 'drone', 'panorama', 'other');
CREATE TYPE hero_type_t           AS ENUM ('image', 'video', 'slideshow', 'parallax');
CREATE TYPE layout_style_t        AS ENUM ('fullwidth', 'boxed', 'magazine', 'editorial', 'immersive');
CREATE TYPE commentable_type_t    AS ENUM ('destination', 'article', 'review');
CREATE TYPE page_entity_type_t    AS ENUM ('destination', 'article', 'landing_page');
CREATE TYPE visit_type_t          AS ENUM ('solo', 'couple', 'family', 'friends', 'business', 'other');
CREATE TYPE device_type_t         AS ENUM ('desktop', 'tablet', 'mobile', 'bot', 'unknown');
CREATE TYPE setting_data_type_t   AS ENUM ('string', 'integer', 'boolean', 'json', 'text');
CREATE TYPE storage_disk_t        AS ENUM ('local', 's3', 'gcs', 'azure');


-- ============================================================
-- SECTION 1:
<truncated 45215 bytes>
dx_pv_entity     ON page_views (entity_type, entity_id);
CREATE INDEX idx_pv_viewed_at  ON page_views (viewed_at DESC);
CREATE INDEX idx_pv_session_id ON page_views (session_id);


-- ------------------------------------------------------------
-- 13.2  destination_daily_stats  (pre-aggregated)
-- ------------------------------------------------------------
CREATE TABLE destination_daily_stats (
    id                   BIGINT   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id       BIGINT   NOT NULL,
    stat_date            DATE     NOT NULL,
    view_count           INTEGER  NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    unique_visitors      INTEGER  NOT NULL DEFAULT 0 CHECK (unique_visitors >= 0),
    mobile_views         INTEGER  NOT NULL DEFAULT 0 CHECK (mobile_views >= 0),
    desktop_views        INTEGER  NOT NULL DEFAULT 0 CHECK (desktop_views >= 0),
    new_reviews          SMALLINT NOT NULL DEFAULT 0 CHECK (new_reviews >= 0),
    new_favorites        SMALLINT NOT NULL DEFAULT 0 CHECK (new_favorites >= 0),
    new_comments         SMALLINT NOT NULL DEFAULT 0 CHECK (new_comments >= 0),
    avg_session_seconds  SMALLINT CHECK (avg_session_seconds >= 0),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_dds_dest_date   UNIQUE (destination_id, stat_date),
    CONSTRAINT fk_dds_destination FOREIGN KEY (destination_id)
        REFERENCES destinations (id) ON DELETE CASCADE
);

COMMENT ON TABLE destination_daily_stats IS 'Daily aggregated metrics per destination';

CREATE INDEX idx_dds_stat_date ON destination_daily_stats (stat_date DESC);

CREATE TRIGGER trg_destination_daily_stats_updated_at
    BEFORE UPDATE ON destination_daily_stats
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();


-- -----------------------------------------------------
<truncated 15716 bytes>

NOTE: The output was truncated because it was too long. Use a more targeted query or a smaller range to get the information you need.
